In [1]:
import pandas as pd

In [17]:
df = pd.read_csv('data.csv')
#df = df.head(5)

In [18]:
df

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    NaN   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    NaN  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    NaN  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    NaN  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    NaN   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    NaN   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    NaN  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [19]:
#df = df.tail(5)
#df

In [20]:
df.describe()

           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000

In [21]:
df.dtypes

Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object

In [22]:
###Handling missing values

df.isnull()

     Date  Category  Value  Product  Sales  Region
0   False     False  False    False  False   False
1   False     False  False    False  False   False
2   False     False  False    False  False   False
3   False     False  False    False  False   False
4   False     False  False    False  False   False
5   False     False  False    False  False   False
6   False     False  False    False  False   False
7   False     False  False    False  False   False
8   False     False  False    False  False   False
9   False     False  False    False  False   False
10  False     False  False    False  False   False
11  False     False  False    False   True   False
12  False     False  False    False  False   False
13  False     False  False    False  False   False
14  False     False  False    False  False   False
15  False     False   True    False  False   False
16  False     False  False    False  False   False
17  False     False   True    False  False   False
18  False     False  False    False  False   False
19  False     False  False    False  False   False
20  False     False  False    False  False   False
21  False     False  False    False  False   False
22  False     False  False    False  False   False
23  False     False  False    False  False   False
24  False     False  False    False  False   False
25  False     False  False    False  False   False
26  False     False  False    False  False   False
27  False     False  False    False  False   False
28  False     False   True    False  False   False
29  False     False  False    False  False   False
30  False     False  False    False  False   False
31  False     False  False    False  False   False
32  False     False  False    False  False   False
33  False     False  False    False   True   False
34  False     False  False    False  False   False
35  False     False  False    False   True   False
36  False     False  False    False  False   False
37  False     False  False    False   True   False
38  False     False  False    False  False   False
39  False     False  False    False  False   False
40  False     False  False    False  False   False
41  False     False  False    False  False   False
42  False     False  False    False  False   False
43  False     False  False    False  False   False
44  False     False  False    False  False   False
45  False     False  False    False  False   False
46  False     False  False    False  False   False
47  False     False  False    False  False   False
48  False     False  False    False  False   False
49  False     False  False    False  False   False

In [23]:
df[df.isnull()]

   Date Category  Value Product  Sales Region
0   NaN      NaN    NaN     NaN    NaN    NaN
1   NaN      NaN    NaN     NaN    NaN    NaN
2   NaN      NaN    NaN     NaN    NaN    NaN
3   NaN      NaN    NaN     NaN    NaN    NaN
4   NaN      NaN    NaN     NaN    NaN    NaN
5   NaN      NaN    NaN     NaN    NaN    NaN
6   NaN      NaN    NaN     NaN    NaN    NaN
7   NaN      NaN    NaN     NaN    NaN    NaN
8   NaN      NaN    NaN     NaN    NaN    NaN
9   NaN      NaN    NaN     NaN    NaN    NaN
10  NaN      NaN    NaN     NaN    NaN    NaN
11  NaN      NaN    NaN     NaN    NaN    NaN
12  NaN      NaN    NaN     NaN    NaN    NaN
13  NaN      NaN    NaN     NaN    NaN    NaN
14  NaN      NaN    NaN     NaN    NaN    NaN
15  NaN      NaN    NaN     NaN    NaN    NaN
16  NaN      NaN    NaN     NaN    NaN    NaN
17  NaN      NaN    NaN     NaN    NaN    NaN
18  NaN      NaN    NaN     NaN    NaN    NaN
19  NaN      NaN    NaN     NaN    NaN    NaN
20  NaN      NaN    NaN     NaN    NaN    NaN
21  NaN      NaN    NaN     NaN    NaN    NaN
22  NaN      NaN    NaN     NaN    NaN    NaN
23  NaN      NaN    NaN     NaN    NaN    NaN
24  NaN      NaN    NaN     NaN    NaN    NaN
25  NaN      NaN    NaN     NaN    NaN    NaN
26  NaN      NaN    NaN     NaN    NaN    NaN
27  NaN      NaN    NaN     NaN    NaN    NaN
28  NaN      NaN    NaN     NaN    NaN    NaN
29  NaN      NaN    NaN     NaN    NaN    NaN
30  NaN      NaN    NaN     NaN    NaN    NaN
31  NaN      NaN    NaN     NaN    NaN    NaN
32  NaN      NaN    NaN     NaN    NaN    NaN
33  NaN      NaN    NaN     NaN    NaN    NaN
34  NaN      NaN    NaN     NaN    NaN    NaN
35  NaN      NaN    NaN     NaN    NaN    NaN
36  NaN      NaN    NaN     NaN    NaN    NaN
37  NaN      NaN    NaN     NaN    NaN    NaN
38  NaN      NaN    NaN     NaN    NaN    NaN
39  NaN      NaN    NaN     NaN    NaN    NaN
40  NaN      NaN    NaN     NaN    NaN    NaN
41  NaN      NaN    NaN     NaN    NaN    NaN
42  NaN      NaN    NaN     NaN    NaN    NaN
43  NaN      NaN    NaN     NaN    NaN    NaN
44  NaN      NaN    NaN     NaN    NaN    NaN
45  NaN      NaN    NaN     NaN    NaN    NaN
46  NaN      NaN    NaN     NaN    NaN    NaN
47  NaN      NaN    NaN     NaN    NaN    NaN
48  NaN      NaN    NaN     NaN    NaN    NaN
49  NaN      NaN    NaN     NaN    NaN    NaN

In [24]:
df.isnull().any()

Date        False
Category    False
Value        True
Product     False
Sales        True
Region      False
dtype: bool

In [25]:
df.isnull().sum()

Date        0
Category    0
Value       3
Product     0
Sales       4
Region      0
dtype: int64

In [26]:
df.fillna(0)

          Date Category  Value   Product  Sales Region
0   2023-01-01        A   28.0  Product1  754.0   East
1   2023-01-02        B   39.0  Product3  110.0  North
2   2023-01-03        C   32.0  Product2  398.0   East
3   2023-01-04        B    8.0  Product1  522.0   East
4   2023-01-05        B   26.0  Product3  869.0  North
5   2023-01-06        B   54.0  Product3  192.0   West
6   2023-01-07        A   16.0  Product1  936.0   East
7   2023-01-08        C   89.0  Product1  488.0   West
8   2023-01-09        C   37.0  Product3  772.0   West
9   2023-01-10        A   22.0  Product2  834.0   West
10  2023-01-11        B    7.0  Product1  842.0  North
11  2023-01-12        B   60.0  Product2    0.0   West
12  2023-01-13        A   70.0  Product3  628.0  South
13  2023-01-14        A   69.0  Product1  423.0   East
14  2023-01-15        A   47.0  Product2  893.0   West
15  2023-01-16        C    0.0  Product1  895.0  North
16  2023-01-17        C   93.0  Product2  511.0  South
17  2023-01-18        C    0.0  Product1  108.0   West
18  2023-01-19        A   31.0  Product2  578.0   West
19  2023-01-20        A   59.0  Product1  736.0   East
20  2023-01-21        C   82.0  Product3  606.0  South
21  2023-01-22        C   37.0  Product2  992.0  South
22  2023-01-23        B   62.0  Product3  942.0  North
23  2023-01-24        C   92.0  Product2  342.0   West
24  2023-01-25        A   24.0  Product2  458.0   East
25  2023-01-26        C   95.0  Product1  584.0   West
26  2023-01-27        C   71.0  Product2  619.0  North
27  2023-01-28        C   56.0  Product2  224.0  North
28  2023-01-29        B    0.0  Product3  617.0  North
29  2023-01-30        C   51.0  Product2  737.0  South
30  2023-01-31        B   50.0  Product3  735.0   West
31  2023-02-01        A   17.0  Product2  189.0   West
32  2023-02-02        B   63.0  Product3  338.0  South
33  2023-02-03        C   27.0  Product3    0.0   East
34  2023-02-04        C   70.0  Product3  669.0   West
35  2023-02-05        B   60.0  Product2    0.0   West
36  2023-02-06        C   36.0  Product3  177.0   East
37  2023-02-07        C    2.0  Product1    0.0  North
38  2023-02-08        C   94.0  Product1  408.0  South
39  2023-02-09        A   62.0  Product1  155.0   West
40  2023-02-10        B   15.0  Product1  578.0   East
41  2023-02-11        C   97.0  Product1  256.0   East
42  2023-02-12        A   93.0  Product3  164.0   West
43  2023-02-13        A   43.0  Product3  949.0   East
44  2023-02-14        A   96.0  Product3  830.0   East
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [27]:
### Filling missing values with the mean of the column

df['Sales_fillNa']=df['Sales'].fillna(df['Sales'].mean())
df

          Date Category  Value   Product  Sales Region  Sales_fillNa
0   2023-01-01        A   28.0  Product1  754.0   East    754.000000
1   2023-01-02        B   39.0  Product3  110.0  North    110.000000
2   2023-01-03        C   32.0  Product2  398.0   East    398.000000
3   2023-01-04        B    8.0  Product1  522.0   East    522.000000
4   2023-01-05        B   26.0  Product3  869.0  North    869.000000
5   2023-01-06        B   54.0  Product3  192.0   West    192.000000
6   2023-01-07        A   16.0  Product1  936.0   East    936.000000
7   2023-01-08        C   89.0  Product1  488.0   West    488.000000
8   2023-01-09        C   37.0  Product3  772.0   West    772.000000
9   2023-01-10        A   22.0  Product2  834.0   West    834.000000
10  2023-01-11        B    7.0  Product1  842.0  North    842.000000
11  2023-01-12        B   60.0  Product2    NaN   West    557.130435
12  2023-01-13        A   70.0  Product3  628.0  South    628.000000
13  2023-01-14        A   69.0  Product1  423.0   East    423.000000
14  2023-01-15        A   47.0  Product2  893.0   West    893.000000
15  2023-01-16        C    NaN  Product1  895.0  North    895.000000
16  2023-01-17        C   93.0  Product2  511.0  South    511.000000
17  2023-01-18        C    NaN  Product1  108.0   West    108.000000
18  2023-01-19        A   31.0  Product2  578.0   West    578.000000
19  2023-01-20        A   59.0  Product1  736.0   East    736.000000
20  2023-01-21        C   82.0  Product3  606.0  South    606.000000
21  2023-01-22        C   37.0  Product2  992.0  South    992.000000
22  2023-01-23        B   62.0  Product3  942.0  North    942.000000
23  2023-01-24        C   92.0  Product2  342.0   West    342.000000
24  2023-01-25        A   24.0  Product2  458.0   East    458.000000
25  2023-01-26        C   95.0  Product1  584.0   West    584.000000
26  2023-01-27        C   71.0  Product2  619.0  North    619.000000
27  2023-01-28        C   56.0  Product2  224.0  North    224.000000
28  2023-01-29        B    NaN  Product3  617.0  North    617.000000
29  2023-01-30        C   51.0  Product2  737.0  South    737.000000
30  2023-01-31        B   50.0  Product3  735.0   West    735.000000
31  2023-02-01        A   17.0  Product2  189.0   West    189.000000
32  2023-02-02        B   63.0  Product3  338.0  South    338.000000
33  2023-02-03        C   27.0  Product3    NaN   East    557.130435
34  2023-02-04        C   70.0  Product3  669.0   West    669.000000
35  2023-02-05        B   60.0  Product2    NaN   West    557.130435
36  2023-02-06        C   36.0  Product3  177.0   East    177.000000
37  2023-02-07        C    2.0  Product1    NaN  North    557.130435
38  2023-02-08        C   94.0  Product1  408.0  South    408.000000
39  2023-02-09        A   62.0  Product1  155.0   West    155.000000
40  2023-02-10        B   15.0  Product1  578.0   East    578.000000
41  2023-02-11        C   97.0  Product1  256.0   East    256.000000
42  2023-02-12        A   93.0  Product3  164.0   West    164.000000
43  2023-02-13        A   43.0  Product3  949.0   East    949.000000
44  2023-02-14        A   96.0  Product3  830.0   East    830.000000
45  2023-02-15        B   99.0  Product2  599.0   West    599.000000
46  2023-02-16        B    6.0  Product1  938.0  South    938.000000
47  2023-02-17        B   69.0  Product3  143.0   West    143.000000
48  2023-02-18        C   65.0  Product3  182.0  North    182.000000
49  2023-02-19        C   11.0  Product3  708.0  North    708.000000

In [28]:
df.dtypes

Date             object
Category         object
Value           float64
Product          object
Sales           float64
Region           object
Sales_fillNa    float64
dtype: object

In [30]:
## Renaming columns 

df = df.rename(columns={'Date':'Sale Date'})

In [31]:
df

     Sale Date Category  Value   Product  Sales Region  Sales_fillNa
0   2023-01-01        A   28.0  Product1  754.0   East    754.000000
1   2023-01-02        B   39.0  Product3  110.0  North    110.000000
2   2023-01-03        C   32.0  Product2  398.0   East    398.000000
3   2023-01-04        B    8.0  Product1  522.0   East    522.000000
4   2023-01-05        B   26.0  Product3  869.0  North    869.000000
5   2023-01-06        B   54.0  Product3  192.0   West    192.000000
6   2023-01-07        A   16.0  Product1  936.0   East    936.000000
7   2023-01-08        C   89.0  Product1  488.0   West    488.000000
8   2023-01-09        C   37.0  Product3  772.0   West    772.000000
9   2023-01-10        A   22.0  Product2  834.0   West    834.000000
10  2023-01-11        B    7.0  Product1  842.0  North    842.000000
11  2023-01-12        B   60.0  Product2    NaN   West    557.130435
12  2023-01-13        A   70.0  Product3  628.0  South    628.000000
13  2023-01-14        A   69.0  Product1  423.0   East    423.000000
14  2023-01-15        A   47.0  Product2  893.0   West    893.000000
15  2023-01-16        C    NaN  Product1  895.0  North    895.000000
16  2023-01-17        C   93.0  Product2  511.0  South    511.000000
17  2023-01-18        C    NaN  Product1  108.0   West    108.000000
18  2023-01-19        A   31.0  Product2  578.0   West    578.000000
19  2023-01-20        A   59.0  Product1  736.0   East    736.000000
20  2023-01-21        C   82.0  Product3  606.0  South    606.000000
21  2023-01-22        C   37.0  Product2  992.0  South    992.000000
22  2023-01-23        B   62.0  Product3  942.0  North    942.000000
23  2023-01-24        C   92.0  Product2  342.0   West    342.000000
24  2023-01-25        A   24.0  Product2  458.0   East    458.000000
25  2023-01-26        C   95.0  Product1  584.0   West    584.000000
26  2023-01-27        C   71.0  Product2  619.0  North    619.000000
27  2023-01-28        C   56.0  Product2  224.0  North    224.000000
28  2023-01-29        B    NaN  Product3  617.0  North    617.000000
29  2023-01-30        C   51.0  Product2  737.0  South    737.000000
30  2023-01-31        B   50.0  Product3  735.0   West    735.000000
31  2023-02-01        A   17.0  Product2  189.0   West    189.000000
32  2023-02-02        B   63.0  Product3  338.0  South    338.000000
33  2023-02-03        C   27.0  Product3    NaN   East    557.130435
34  2023-02-04        C   70.0  Product3  669.0   West    669.000000
35  2023-02-05        B   60.0  Product2    NaN   West    557.130435
36  2023-02-06        C   36.0  Product3  177.0   East    177.000000
37  2023-02-07        C    2.0  Product1    NaN  North    557.130435
38  2023-02-08        C   94.0  Product1  408.0  South    408.000000
39  2023-02-09        A   62.0  Product1  155.0   West    155.000000
40  2023-02-10        B   15.0  Product1  578.0   East    578.000000
41  2023-02-11        C   97.0  Product1  256.0   East    256.000000
42  2023-02-12        A   93.0  Product3  164.0   West    164.000000
43  2023-02-13        A   43.0  Product3  949.0   East    949.000000
44  2023-02-14        A   96.0  Product3  830.0   East    830.000000
45  2023-02-15        B   99.0  Product2  599.0   West    599.000000
46  2023-02-16        B    6.0  Product1  938.0  South    938.000000
47  2023-02-17        B   69.0  Product3  143.0   West    143.000000
48  2023-02-18        C   65.0  Product3  182.0  North    182.000000
49  2023-02-19        C   11.0  Product3  708.0  North    708.000000

In [32]:
df.head()

    Sale Date Category  Value   Product  Sales Region  Sales_fillNa
0  2023-01-01        A   28.0  Product1  754.0   East         754.0
1  2023-01-02        B   39.0  Product3  110.0  North         110.0
2  2023-01-03        C   32.0  Product2  398.0   East         398.0
3  2023-01-04        B    8.0  Product1  522.0   East         522.0
4  2023-01-05        B   26.0  Product3  869.0  North         869.0

In [33]:
### Change the datatypes

df['Value_new']=df['Value'].astype(float)
df.head()

    Sale Date Category  Value   Product  Sales Region  Sales_fillNa  Value_new
0  2023-01-01        A   28.0  Product1  754.0   East         754.0       28.0
1  2023-01-02        B   39.0  Product3  110.0  North         110.0       39.0
2  2023-01-03        C   32.0  Product2  398.0   East         398.0       32.0
3  2023-01-04        B    8.0  Product1  522.0   East         522.0        8.0
4  2023-01-05        B   26.0  Product3  869.0  North         869.0       26.0

In [34]:
df['New_value'] = df['Value'].apply(lambda x:x*2)
df.head()

,Sale Date,Category,Value,Product,Sales,Region,Sales_fillNa,Value_new,New_value
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28.0,56.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39.0,78.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32.0,64.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8.0,16.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26.0,52.0

In [35]:
###Data Aggregrating and Grouping 

df.head()

,Sale Date,Category,Value,Product,Sales,Region,Sales_fillNa,Value_new,New_value
0,2023-01-01,A,28.0,Product1,754.0,East,754.0,28.0,56.0
1,2023-01-02,B,39.0,Product3,110.0,North,110.0,39.0,78.0
2,2023-01-03,C,32.0,Product2,398.0,East,398.0,32.0,64.0
3,2023-01-04,B,8.0,Product1,522.0,East,522.0,8.0,16.0
4,2023-01-05,B,26.0,Product3,869.0,North,869.0,26.0,52.0

In [37]:
grouped_mean = df.groupby('Product')['Value'].mean()
print(grouped_mean)

Product
Product1    46.214286
Product2    52.800000
Product3    55.166667
Name: Value, dtype: float64

In [39]:
grouped_sum=df.groupby(['Product','Region']).sum()
print(grouped_sum)

                                                         Sale Date  Category  \
Product  Region
Product1 East    2023-01-012023-01-042023-01-072023-01-142023-0...   ABAAABC
         North                      2023-01-112023-01-162023-02-07       BCC
         South                                2023-02-082023-02-16        CB
         West             2023-01-082023-01-182023-01-262023-02-09      CCCA
Product2 East                                 2023-01-032023-01-25        CA
         North                                2023-01-272023-01-28        CC
         South                      2023-01-172023-01-222023-01-30       CCC
         West    2023-01-102023-01-122023-01-152023-01-192023-0...  ABAACABB
Product3 East             2023-02-032023-02-062023-02-132023-02-14      CCAA
         North   2023-01-022023-01-052023-01-232023-01-292023-0...    BBBBCC
         South                      2023-01-132023-01-212023-02-02       ACB
         West    2023-01-062023-01-092023-01-312023-02-042023-0...    BCBCAB

                 Value   Sales  Sales_fillNa  Value_new  New_value
Product  Region
Product1 East    292.0  4205.0   4205.000000      292.0      584.0
         North     9.0  1737.0   2294.130435        9.0       18.0
         South   100.0  1346.0   1346.000000      100.0      200.0
         West    246.0  1335.0   1335.000000      246.0      492.0
Product2 East     56.0   856.0    856.000000       56.0      112.0
         North   127.0   843.0    843.000000      127.0      254.0
         South   181.0  2240.0   2240.000000      181.0      362.0
         West    428.0  3435.0   4549.260870      428.0      856.0
Product3 East    202.0  1956.0   2513.130435      202.0      404.0
         North   203.0  3428.0   3428.000000      203.0      406.0
         South   215.0  1572.0   1572.000000      215.0      430.0
         West    373.0  2675.0   2675.000000      373.0      746.0

In [41]:
grouped_m=df.groupby(['Product','Region'])['Value'].mean()
print(grouped_m)

Product   Region
Product1  East      41.714286
          North      4.500000
          South     50.000000
          West      82.000000
Product2  East      28.000000
          North     63.500000
          South     60.333333
          West      53.500000
Product3  East      50.500000
          North     40.600000
          South     71.666667
          West      62.166667
Name: Value, dtype: float64

In [42]:
### Aggregrate multiple functions 

grouped_agg = df.groupby('Region')['Value'].aggregate(['mean','sum','count'])
print(grouped_agg)

             mean     sum  count
Region
East    42.307692   550.0     13
North   37.666667   339.0      9
South   62.000000   496.0      8
West    61.588235  1047.0     17

In [43]:
### Merging and joining Dataframes

df1 = pd.DataFrame({'Key': ['A','B','C'], 'Value': [1,2,3]})

df2 = pd.DataFrame({'Key': ['A','B','D'], 'Value': [4,5,6]})

In [44]:
df1

  Key  Value
0   A      1
1   B      2
2   C      3

In [45]:
df2

  Key  Value
0   A      4
1   B      5
2   D      6

In [46]:
### Merge dataframe on the 'Key Columns' 

pd.merge(df1,df2,on="Key",how="inner")

  Key  Value_x  Value_y
0   A        1        4
1   B        2        5

In [47]:
pd.merge(df1,df2,on="Key",how="outer")

  Key  Value_x  Value_y
0   A      1.0      4.0
1   B      2.0      5.0
2   C      3.0      NaN
3   D      NaN      6.0

In [48]:
pd.merge(df1,df2,on="Key",how="left")

  Key  Value_x  Value_y
0   A        1      4.0
1   B        2      5.0
2   C        3      NaN

In [49]:
pd.merge(df1,df2,on="Key",how="right")

  Key  Value_x  Value_y
0   A      1.0        4
1   B      2.0        5
2   D      NaN        6