In [1]:
##Pandas is used for data analysis and data cleaning. Provides series and dataframe.

In [2]:
import pandas as pd

In [4]:
## Series is a 1D array like object that can hold any datatype.

import pandas as pd 

data = [1,2,3,4,5]
series=pd.Series(data)
print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [5]:
##Creating a series from dictionary 

data = {'a':1,'b':2,'c':3}
series = pd.Series(data)
print(series)

a    1
b    2
c    3
dtype: int64

In [6]:
data = [10,20,30]
index = ['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [7]:
## Dataframe - 2D - similiar to an excel

## create a dataframe from a dictionary of list 

data = {
    'Name': ['Kinnari','John','Jack'],
    'Age': [23, 21, 19],
    'City':['Mumbai','New York','Baltimore']

}

df = pd.DataFrame(data)
print(df)
print(type(df))

      Name  Age       City
0  Kinnari   23     Mumbai
1     John   21   New York
2     Jack   19  Baltimore
<class 'pandas.core.frame.DataFrame'>

In [8]:
import numpy as np
np.array(df)

array([['Kinnari', 23, 'Mumbai'],
       ['John', 21, 'New York'],
       ['Jack', 19, 'Baltimore']], dtype=object)

In [11]:
##create a data fram from a list of dictionaries 

data = [
    {'Name': 'Kinnari', 'Age': 23, 'City': 'Mumbai'},
    {'Name': 'Kshtija', 'Age': 23, 'City': 'Thane'},
     {'Name': 'Janhavi', 'Age': 24, 'City': 'Baltimore'}
]

df = pd.DataFrame(data)
print(df)

      Name  Age       City
0  Kinnari   23     Mumbai
1  Kshtija   23      Thane
2  Janhavi   24  Baltimore

In [15]:
df = pd.read_csv('data.csv')
print(df.head())

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North

In [13]:
print(df.head())

      Name  Age       City
0  Kinnari   23     Mumbai
1  Kshtija   23      Thane
2  Janhavi   24  Baltimore

In [27]:
### accessing data from dataframe

data = [
    {'Name': 'Kinnari', 'Age': 23, 'City': 'Mumbai'},
    {'Name': 'Kshtija', 'Age': 23, 'City': 'Thane'},
     {'Name': 'Janhavi', 'Age': 24, 'City': 'Baltimore'}
]

df = pd.DataFrame(data)
print(df)

      Name  Age       City
0  Kinnari   23     Mumbai
1  Kshtija   23      Thane
2  Janhavi   24  Baltimore

In [28]:
df

      Name  Age       City
0  Kinnari   23     Mumbai
1  Kshtija   23      Thane
2  Janhavi   24  Baltimore

In [29]:
df['Name']

0    Kinnari
1    Kshtija
2    Janhavi
Name: Name, dtype: object

In [33]:
print(df.loc[0])
print(df.loc[0][0])

Name    Kinnari
Age          23
City     Mumbai
Name: 0, dtype: object
Kinnari

C:\Users\kinnari\AppData\Local\Temp\ipykernel_16616\3310008725.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(df.loc[0][0])

In [34]:
df.iloc[0]

Name    Kinnari
Age          23
City     Mumbai
Name: 0, dtype: object

In [35]:
df.iloc[0][0]

C:\Users\kinnari\AppData\Local\Temp\ipykernel_16616\2900375399.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][0]

'Kinnari'

In [37]:
##accessing a specified element

df

      Name  Age       City
0  Kinnari   23     Mumbai
1  Kshtija   23      Thane
2  Janhavi   24  Baltimore

In [38]:
df.at[1,'Age']

23

In [39]:
df.at[2,'City']

'Baltimore'

In [42]:
## Accessing a specific element using iat

df.iat[0,2]

'Mumbai'

In [43]:
## Data Manipulation 

df['Salary'] = [50000,60000,70000]

In [44]:
df

      Name  Age       City  Salary
0  Kinnari   23     Mumbai   50000
1  Kshtija   23      Thane   60000
2  Janhavi   24  Baltimore   70000

In [47]:
### Remove a column

df.drop('Salary',axis=1)

      Name  Age       City
0  Kinnari   23     Mumbai
1  Kshtija   23      Thane
2  Janhavi   24  Baltimore

In [48]:
df

      Name  Age       City  Salary
0  Kinnari   23     Mumbai   50000
1  Kshtija   23      Thane   60000
2  Janhavi   24  Baltimore   70000

In [49]:
df.drop('Salary',axis=1,inplace=True)

In [50]:
df

      Name  Age       City
0  Kinnari   23     Mumbai
1  Kshtija   23      Thane
2  Janhavi   24  Baltimore

In [52]:
## Add age to the column

df['Age']=df['Age']+1

In [53]:
df

      Name  Age       City
0  Kinnari   24     Mumbai
1  Kshtija   24      Thane
2  Janhavi   25  Baltimore

In [54]:
df.drop(2)

      Name  Age    City
0  Kinnari   24  Mumbai
1  Kshtija   24   Thane

In [55]:
df.drop(2,inplace=True)

In [56]:
df

      Name  Age    City
0  Kinnari   24  Mumbai
1  Kshtija   24   Thane

In [58]:
data = pd.read_csv('data.csv')
print(data.head())
print(data.dtypes)
print(data.describe())  ##Statistical summary
grouped = data.groupby('Category')['Value'].mean()
print(grouped)  ##Mean of Value for each Category

         Date Category  Value   Product  Sales Region
0  2023-01-01        A   28.0  Product1  754.0   East
1  2023-01-02        B   39.0  Product3  110.0  North
2  2023-01-03        C   32.0  Product2  398.0   East
3  2023-01-04        B    8.0  Product1  522.0   East
4  2023-01-05        B   26.0  Product3  869.0  North
Date         object
Category     object
Value       float64
Product      object
Sales       float64
Region       object
dtype: object
           Value       Sales
count  47.000000   46.000000
mean   51.744681  557.130435
std    29.050532  274.598584
min     2.000000  108.000000
25%    27.500000  339.000000
50%    54.000000  591.500000
75%    70.000000  767.500000
max    99.000000  992.000000
Category
A    48.357143
B    44.142857
C    59.842105
Name: Value, dtype: float64